### ISSUE TITLE
exec ./build-repo.sh error

### ISSUE THREAD

**Issue by sreimchangwalker** [YurkoWasHere/tdx-tools#2]
env:
CPU: Intel 8592+
GPU: Nvidia : H20
Linux ver. : Ubuntu 22.04.1 LTS
Linux kernel: Linux ubuntu 6.6.8-060608-generic #202312201634 SMP PREEMPT_DYNAMIC Wed Dec 20 16:47:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

ref  guide-book: https://docs.nvidia.com/cc-deployment-guide-tdx.pdf
In Setting Up the Host OS——Build the Kernel

Because the Intel's official git repository is gone, the git repository you provided is used.

Detail:
```
make: *** [debian/rules.d/2-binary-arch.mk:200: /home/shared/tdx-tools/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v6.2/debian/stamps/stamp-install-generic] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
```

How to solve? Please.

**Comment by sreimchangwalker** [comment]
solved

**Comment by YurkoWasHere** [comment]
There is also a new update of the docs and (hopefully) renders this repo no longer needed.
